### ISSUE TITLE
Improve inference speed

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/kwja#166]
## How

- [x] Load model parameters only once
- [x] Perform padding to the max sequence length in a batch
- [x] Use `torch.inference_mode` (https://pytorch.org/docs/stable/generated/torch.inference_mode.html)
- [x] Use `torch.compile` (https://pytorch.org/docs/stable/generated/torch.compile.html)

**Comment by hkiyomaru** [comment]
> Use `torch.inference_mode`

Pytorch Lightning automatically turns on this feature.
https://lightning.ai/docs/pytorch/latest/common/trainer.html#inference-mode

**Comment by omukazu** [comment]
#172 #
