### ISSUE TITLE
Error message appears when Juman++ and/or KNP are not installed

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/kwja#167]
## What

When attempting to start KWJA, an error message is displayed if Juman++ and/or KNP are not installed. The error message is as follows:

```
failed to start Juman++: [Errno 2] No such file or directory: 'jumanpp'
failed to start KNP: [Errno 2] No such file or directory: 'knp'
```

## Proposed fix

This issue can be fixed by deferring the instantiation of Juman++ and KNP until they are actually needed. Please refer to the following line of code to fix the issue:

https://github.com/ku-nlp/kwja/blob/main/src/kwja/datamodule/datasets/seq2seq_inference.py#L18

**Comment by Taka008** [comment]
PR #169 solves this issue.
